---
title: "Homework 6"
author: "aw3253"
date: "12/4/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"                    
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


# Problem 1

Importing Data:

```{r}
birth =
  read_csv(file = "./data/birthweight.csv") %>% 
  drop_na()
```


Data Cleaning:

```{r}
birth_df =
birth %>% 
  mutate(babysex = factor(babysex,
                          levels = c(1, 2),
                          labels = c("Male", "Female"))) %>% 
  mutate(frace = factor(frace,
                        levels = c(1, 2, 3, 4, 8, 9),
                        labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown"))) %>% 
  mutate(malform = factor(malform,
                          levels = c(0, 1),
                          labels = c("Absent", "Present"))) %>% 
  mutate(mrace = factor(mrace,
                        levels = c(1, 2, 3, 4, 8),
                        labels = c("White", "Black", "Asian", "Puerto Rican", "Other")))

birth_df
```


Proposed Model for Birthweight:

```{r}
fit= lm(bwt ~ gaweeks+ smoken + delwt + pnumlbw + wtgain + momage, data = birth_df)
fit %>% broom::tidy()
fit %>% broom::glance()
```




Plotting Residuals:

```{r}
residual_plot =
birth_df %>% 
  add_predictions(fit) %>% 
  add_residuals(fit) %>% 
  ggplot(aes(x=pred, y=resid)) +
  geom_point()  +
  geom_smooth(method= "lm", se = FALSE) +
  labs(x= "Predicted Birthweight(grams)", y="Residual",title = "Predictions of Proposed Model vs Residuals")

residual_plot
```

The residuals are somewhat randomly scattered around 0, but there does seem to be a cluster indicating a pattern. Based on other assumptions, the model may still be appropriate. 


Comparing Models:

```{r}
main = lm(bwt ~ blength + gaweeks, data=birth_df)

interaction = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex, data=birth_df)
```

```{r}
cv_df =
  crossv_mc(birth_df, n=4342, test = 0.15) %>% 
 
   mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %>% 
 
   mutate(
    fit = map(train, ~lm(bwt ~ gaweeks +  momage + malform + smoken + (smoken*malform), data = birth_df )),
    fixed  = map(train, ~lm(bwt ~ blength + gaweeks, data=birth_df)),
    interaction = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex, data=birth_df))) %>% 
  
  mutate(
    rmse_fit = map2_dbl(fit, test, ~rmse(model = .x, data = .y)),
    rmse_fixed = map2_dbl(fixed, test, ~rmse(model = .x, data = .y)),
    rmse_interaction = map2_dbl(interaction, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_boxplot =
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_boxplot()
cv_boxplot
```



##Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
bootstrap_weather =
  bootstrap(weather_df, 5000) 
as_data_frame(bootstrap_weather$strap[[1]])
```


```{r}
bootstrap_results=
bootstrap_weather %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data=.x)),
    results = map(models, broom::tidy),
    glance = map(models, broom::glance)) %>% 
  select(-strap,-models) %>% 
  unnest(glance,results) %>% 
  group_by(.id)
```

```{r}
bootstrap = 
  bootstrap_results %>% 
  select(.id, estimate, term, r.squared, adj.r.squared) %>% 
  pivot_wider(names_from = term, values_from = estimate) %>% 
  janitor::clean_names() %>% 
  mutate(log_var = log(intercept * tmin)) 
```


```{r}
r_squared_distribution = 
  bootstrap %>% 
  ggplot(aes(x = r_squared)) +
  geom_density(alpha = 0.2) +  
  labs(title = "Distribution of r2")
r_squared_distribution
```
```{r}
log_var_distribution =
  bootstrap %>% 
  ggplot(aes(x = log_var)) +
  geom_density(alpha = 0.2) +
  labs(title = "Distribution of log_var")
log_var_distribution
```
